### ISSUE TITLE
Results of testing the module on Windows 8 

### ISSUE THREAD

**Issue by scriptnull** [KyleRoss/windows-cpu#1]
I have thoroughly tested the module on Windows 8 . The Results are as follows 

|Function | Support |
|------------|------------|
|totalLoad | No |
|nodeLoad | No |
|processLoad | No |
|findLoad|No|
|cpuInfo|Yes|

It will be useful if you comment out  the result of "wmic path Win32_PerfFormattedData_PerfProc_Process get Name,PercentProcessorTime,IDProcess" on a Windows 7 machine , so as to look for an alternative on windows 8.

**Comment by UltimateBrent** [comment]
Just to confirm that this also works on 8.1 32-bit.

**Comment by KyleRoss** [comment]
Seems like it's all working correctly on Win8, I'm going to close this issue. If anyone finds a bug, please open a new issue. Thanks for your help, the Readme will be updated shortly.
