### ISSUE TITLE
Add XP and 10 to README.md

### ISSUE THREAD

**Issue by inexist3nce** [KyleRoss/windows-cpu#10]
#### Windows XP

I have tested `windows-cpu` (using `require` in my script) and it works on XP Professional SP3. It does, however, fail all tests in `mocha test\cpu.js`.

XP Home does not include `wmic`, so I guess this module is completely broken in all Home editions.
#### Windows 10

Windows 10 Pro is working and passing all tests in `mocha test\cpu.js` (but it seems to require administrator rights?).

**Comment by KyleRoss** [comment]
Thanks for testing this, I added them to the readme.
