### ISSUE TITLE
Incorrect no. of processors detected

### ISSUE THREAD

**Issue by sospirited** [KyleRoss/windows-cpu#11]
Machine:

```
Lenovo T430, Windows 7, 64bit
Intel Core i7-3520M CPU @2.90GHz
```

Using NodeJS `v4.2.1`, when calling the snippet of code provided in the docs for `cpuInfo`, my results which get console logged only include a single item in the array of `results` when I would have expected it to be 4 (quad core machine).

Let me know if there's any other bits of debugging you'd like me to carry out to help provide further info on investigating this.

**Comment by streamnsight** [comment]
@sospirited 
looks like it is listing CPUs and not cores. I have a dual Xeon machine and it lists 2 CPUs, not 32 cores.
:-(

**Comment by KyleRoss** [comment]
That is correct @streamnsight, this module only lists physical CPUs and not the cores.
