### ISSUE TITLE
processLoad only showing Node process

### ISSUE THREAD

**Issue by SlickNutter** [KyleRoss/windows-cpu#12]
I'm using processLoad like this:
```
cpu.processLoad(function (error, results) {
    if (error) {
        return console.log(error);
    }
    for (let i = 0; i < results.found.length; ++i)
        console.log(results.found[i].process + " has load " + results.found[i].load);
});
```

My output looks like this:
> node has load 0

I'm running Chrome, VS Code, SourceTree,...

OS: Mocrosoft Windows 10 Pro
Version: 10.0.14393 Build 14393
Processor: Intel Core i5-6400 @2.70Ghz

**Comment by KyleRoss** [comment]
@SlickNutter The `processLoad()` function is to tell you the current load of the running Node process. If you want to see all of the other processes, you should use `totalLoad()` to get the full percentage. In the next version, I may add another function which will return a list of all processes and their current load.
