### ISSUE TITLE
CRITICAL: Install failing when not windows

### ISSUE THREAD

**Issue by flaviocordova** [KyleRoss/windows-cpu#13]
Hi..

I'm not a direct user of windows-cpu but I use pm2-gui that has a dependency to it.
After the new release (from yesterday, I guess) I can't install pm2-gui in a linux machine anymore, because window-cpu fails to install.

The previous version (0.1.4) could be installed in a linux machine.

This is really critical.. :(

**Comment by KyleRoss** [comment]
NPM must have started taking the OS limitation property in the package.json seriously now. I removed that property and released version `0.1.6` and `1.0.1`. You should be able to install now. Let me know if you see any other issues.
