### ISSUE TITLE
process.env.SystemRoot is undefined in unit tests environments

### ISSUE THREAD

**Issue by igorprado** [KyleRoss/windows-cpu#14]
Running unit tests on non-windows environments will always fail the entire test suite:
```
TypeError: Path must be a string. Received undefined
```

Because of this line:
https://github.com/KyleRoss/windows-cpu/blob/master/index.js#L19

`path.join` requires a string, and this env var is undefined in MacOS, for example.

I'm setting this env var manually before running my tests for now.

**Comment by KyleRoss** [comment]
In the latest release (1.1.0), I've defaulted `process.env.SystemRoot` to `/` if undefined. This should fix the issues you were seeing in non-Windows environments. Let me know if you are still seeing issues.
