### ISSUE TITLE
Propose using windows performance counters to drastically improve performance

### ISSUE THREAD

**Issue by SkyLined** [KyleRoss/windows-cpu#4]
Unfortunately, this module is still very CPU intensive after applying the changes suggested in issue #3, especially if you poll the CPU usage frequently.

To get around this, I wrote a node addon that provides a way to access windows performance counters. This allows you to gather CPU usage data very quickly and efficiently, without having to spawn any new processes. It is available at https://github.com/SkyLined/cWinPerfCounter.

This addon does require building from C, but you can pre-build it for various versions of node and processor architectures, and bundle them with your module so the end-user does not have to do this.

Using this code I can poll CPU usage tens of times a second while causing hardly any additional CPU usage: see test.js in the repository for an example.

I'd like to suggest you look into rewriting this module to use Windows performance counters. Feel free to reuse my code, as it's CC0 (in effect there is no copyright whatsoever).

**Comment by KyleRoss** [comment]
I've been looking into this for awhile now, it seems like a better way to grab these stats (or at least faster way). I'm not sure that I want to make a compiled module, but I'm going to try your module out and see if it would make sense to incorporate it. Thanks for your suggestion!

**Comment by marcominetti** [comment]
Hi there, just some code hints...

to get process_name from pid to be used with performance counters...

```javascript
if (process.platform === 'win32') {
  try {
    process.name = require('child_process').execSync('powershell.exe -Command "Get-WmiObject Win32_PerfFormattedData_PerfProc_Process | where-object{ $_.IDProcess -eq ' +
      process.pid + ' } | Format-Table Name,IDProcess -AutoSize -HideTableHeaders"').toString().replace(/\r\n/gi, '').match(/.*?(?=\s)/)[0];
  } catch(error) {
    throw new Error('unable to get process name: please make sure powershell.exe and WMI stack is installed');
  }
}
```

and to get processor usage for the process

```javascript
var processor_pc = new native.perfcounter('\\Process('+process.name+')\\% Processor Time');
var user_pc = new native.perfcounter('\\Process('+process.name+')\\% User Time');
var privileged_pc = new native.perfcounter('\\Process('+process.name+')\\% Privileged Time');
try {
  _total = processor_pc.fnGetValue();
} catch(ex){}
try {
  _user = user_pc.fnGetValue();
} catch(ex){}
try {
  _system = privileged_pc.fnGetValue();
} catch(ex){}
```

I've experienced that I need to invoke fnGetValue() twice to "enable" the performance counter (bypassing exception at first attempts)...

**Comment by KyleRoss** [comment]
I don't foresee this module utilizing performance counters. I'm no longer working on apps or developing in Windows so I'm not personally using this module anymore, I am just keeping it updated. If someone who is more familiar with Windows would like to incorporate performance counters into this module via a pull request, I'm all for it. But for now, I am going to close this issue.
