### ISSUE TITLE
Server 2003 Testing

### ISSUE THREAD

**Issue by susnick** [KyleRoss/windows-cpu#8]
Hoping you can help out here. So I run the command directly in command prompt "wmic path Win32_PerfFormattedData_PerfProc_Process get Name,PercentProcessorTime,IDProcess | findstr /i /c:mapatitlecertimport"

This gives me the expected results. When running with child_process.exec, it just hangs. Its like the callback for exec never gets called.

here is what I ran:

``` javascript
var exec = require('child_process').exec;
var cmd = "wmic path Win32_PerfFormattedData_PerfProc_Process get Name,PercentProcessorTime,IDProcess | findstr /i /c:mapatitlecertimport";

exec(cmd, function (error, stdout, stderr) {
  console.log('stdout: ' + stdout);
  console.log('stderr: ' + stderr);
  if (error !== null) {
    console.log('exec error: ' + error);
  }
});
```

**Comment by KyleRoss** [comment]
Everything looks correct to me. The only thing I can think of that would be causing that issue is if you are **not** running the node snippet above as an administrator.

**Comment by susnick** [comment]
Unfortunately I did run as admin.

**Comment by KyleRoss** [comment]
If this is still an issue, please feel free to reopen. Thanks!
