### ISSUE TITLE
Windows XP testing

### ISSUE THREAD

**Issue by bensoy** [KyleRoss/windows-cpu#9]
Since WMI support is too narrow and tools are not available on Windows XP Home machines, any command of wmic is not working. I tried some hacky ways to install those components but I couldn't make it work in anyways. I tested this on a Windows XP Home Edition SP3 x86 system and unfortunately its not working. However, you may need a new test for XP Professional because I heard that edition has some support for wmi tool and wmic commands so things may be well for XP Pro systems.

**Comment by KyleRoss** [comment]
You are correct, I've updated the readme to reflect this. Thanks for letting me know!
